title: Xianping
# email: axpzhang@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Cost-effective hybrid cloud computing and resource scheduling on Kubernetes.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://axpz.github.io" # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: Axpz
# github_username:  Axpz

# Build settings
theme: minima
plugins:
  - jekyll-feed      # Enable RSS feed plugin for posts
  # - jekyll-sitemap   # Automatically generate sitemap.xml for SEO
  - jekyll-paginate

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

include: 
  - _pages/

# Markdown settings
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false